Remove compiler warnings. Compute checksum internally. Replacing CmdGuidelineViewState by state set/reset

diff --git a/src/build_and_run_all_cli_tests b/src/build_and_run_all_cli_tests
--- a/src/build_and_run_all_cli_tests
+++ b/src/build_and_run_all_cli_tests
@@ -11,6 +11,7 @@
 # Test names. Specify a single test to run just that test
 testsAvailable=( \
     TestCorrelation  \
+    TestCrc32 \
     TestExport \
     TestExportAlign \
     TestFitting \
@@ -36,11 +37,11 @@ testsSelected=()
 while test $# -gt 0
 do
     case "$1" in
-	jpeg2000) CONFIGARGS="CONFIG+=jpeg2000 $CONFIGARGS"
-	    ;;
+        jpeg2000) CONFIGARGS="CONFIG+=jpeg2000 $CONFIGARGS"
+            ;;
         pdf) CONFIGARGS="CONFIG+=pdf $CONFIGARGS"
              ;;
-	*) testsSelected+=("$1")
+        *) testsSelected+=("$1")
     esac
     shift
 done
@@ -90,18 +91,18 @@ else
     # Build and run each test
     for t in "${testsSelected[@]}"
     do
-	sed "s/TEST/$t/g" engauge_test_template.pro >engauge_test.pro
-	qmake $CONFIGARGS engauge_test.pro
-	make -j4 all 2>>$LOGFILE >/dev/null || {
-	    echo "FAIL   : Compilation error is described in build_and_run_all_cli_tests.log"
-	    echo "         Testing will be stopped"
-	    exit 1
+        sed "s/TEST/$t/g" engauge_test_template.pro >engauge_test.pro
+        qmake $CONFIGARGS engauge_test.pro
+        make -j4 all 2>>$LOGFILE >/dev/null || {
+            echo "FAIL   : Compilation error is described in build_and_run_all_cli_tests.log"
+            echo "         Testing will be stopped"
+            exit 1
         }
-	# sed is used to add color to PASS and FAIL. 'Using QtTest' lines are dropped
-	../bin/$t | sed "s/PASS   :/$(tput setaf 2)PASS$(tput sgr0)   :/" | sed "s/FAIL   :/$(tput setaf 1)FAIL$(tput sgr0)   :/" | grep -v 'Using QtTest'
-	if [ $selectedCount -ne 1 ]
-	then
+        # sed is used to add color to PASS and FAIL. 'Using QtTest' lines are dropped
+        ../bin/$t | sed "s/PASS   :/$(tput setaf 2)PASS$(tput sgr0)   :/" | sed "s/FAIL   :/$(tput setaf 1)FAIL$(tput sgr0)   :/" | grep -v 'Using QtTest'
+        if [ $selectedCount -ne 1 ]
+        then
             rm engauge_test.pro
-	fi
+        fi
     done
 fi
